Handle missing `_meta` attribute on `Model` classes
On some `Model` classes, d2a throws the following error:

```
AttributeError: type object 'Model' has no attribute '_meta'
```

Now we check for the presence of the `_meta` attribute.